### ISSUE TITLE
Errors when trying to build the project

### ISSUE THREAD

**Issue by CamiciaNera** [linux-link/CarLauncher#1]
I'm trying to build the project with the last version of Android Studio but there are some errors:

AAPT: error: style attribute 'attr/textAppearanceGridItem (aka com.android.car.carlauncher:attr/textAppearanceGridItem)' not found
AAPT: error: style attribute 'attr/textAppearanceGridItemSecondary (aka com.android.car.carlauncher:attr/textAppearanceGridItemSecondary)' not found
AAPT: error: style attribute 'attr/textAppearanceGridItem (aka com.android.car.carlauncher:attr/textAppearanceGridItem)' not found
AAPT: error: style attribute 'attr/textAppearanceGridItemSecondary (aka com.android.car.carlauncher:attr/textAppearanceGridItemSecondary)' not found

These are 4 of the many errors that prevent compilation

**Comment by thanvanlong** [comment]
have you find solution ?

**Comment by linxu-link** [comment]
This project cannot be compiled. It was originally created just to make it easier to read the code. Sorry for causing trouble to you
